config/routes.rb
Boxroom::Application.routes.draw do
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/folders/:id/new', :to => 'folders#new'

  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]

  resources :permissions, :only => :update_multiple do
    collection do
      put :update_multiple
    end
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  root :to => "folders#index"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree :order => 'name'

  has_many :user_files, :dependent => :destroy, :order => 'attachment_file_name'
  has_many :permissions, :dependent => :destroy

  attr_accessible :name, :user_id

  validates_uniqueness_of :name, :scope => :parent_id
  validates_presence_of :name

  before_save :check_for_parent
  after_create :create_permissions

  def readonly?
    true if is_root? && !new_record?
  end

  def is_root?
    parent.nil?
  end

  def has_children?
    children.count > 0
  end

  def self.root
    find_by_name_and_parent_id('Root folder', nil)
  end

  private

  def check_for_parent
    raise 'Folders must have a parent.' if parent.nil? && name != 'Root folder'
  end

  def create_permissions
    unless is_root?
      parent.permissions.each do |permission|
        Permission.create! do |p|
          p.group = permission.group
          p.folder = self
          p.can_create = permission.can_create
          p.can_read = permission.can_read
          p.can_update = permission.can_update
          p.can_delete = permission.can_delete
        end
      end
    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :require_existing_folder, :only => [:show, :edit, :update, :destroy]
  before_filter :require_existing_parent_folder, :only => [:new, :create]
  before_filter :require_folder_isnt_root_folder, :only => [:edit, :update, :destroy]

  before_filter :require_create_permission, :only => [:new, :create]
  before_filter :require_read_permission, :only => :show
  before_filter :require_update_permission, :only => [:edit, :update]
  before_filter :require_delete_permission, :only => :destroy

  # GET /folder
  def index
    redirect_to folder_url(Folder.root)
  end

  # GET /folders/:id
  # Note: @folder is set in require_existing_folder
  def show
  end

  # GET /folders/:id/folders/new
  # Note: @parent_folder is set in require_existing_parent_folder
  def new
    @folder = @parent_folder.children.build
  end

  # POST /folders/:id/folders
  # Note: @parent_folder is set in require_existing_parent_folder
  def create
    @folder = @parent_folder.children.build(params[:folder])

    if @folder.save
      redirect_to folder_url(@parent_folder)
    else
      render :action => 'new'
    end
  end

  # GET /folders/:id/edit
  # Note: @folder is set in require_existing_folder
  def edit
  end

  # PUT /folders/:id
  # Note: @folder is set in require_existing_folder
  def update
    if @folder.update_attributes(params[:folder])
      redirect_to edit_folder_url(@folder), :notice => 'Your changes were saved successfully.'
    else
      render :action => 'edit'
    end
  end

  # DELETE /folder/:id
  # Note: @folder is set in require_existing_folder
  def destroy
    parent_folder = @folder.parent
    @folder.destroy
    redirect_to folder_url(parent_folder)
  end

  private

  def require_existing_folder
    @folder = Folder.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to folder_url(Folder.root), :alert => 'Someone else deleted this folder. Your action was cancelled.'
  end

  def require_folder_isnt_root_folder
    if @folder.is_root?
      redirect_to folder_url(Folder.root), :alert => 'The root folder cannot be deleted or renamed.'
    end
  end

  # Overrides require_delete_permission in ApplicationController
  def require_delete_permission
    unless current_user.can_delete(@folder) || @folder.is_root?
      redirect_to folder_url(@folder.parent), :alert => "You don't have delete permissions for this folder."
    else
      require_delete_permissions_for(@folder.children)
    end
  end

  def require_delete_permissions_for(folders)
    folders.each do |folder|
      unless current_user.can_delete(folder)
        redirect_to folder_url(@folder.parent), :alert => "You don't have delete permissions for one of the subfolders."
      else
        # Recursive...
        require_delete_permissions_for(folder.children)
      end
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
  def breadcrumbs(folder, breadcrumbs = '')
    breadcrumbs = "<span class=\"breadcrumb nowrap\">#{link_to(folder.parent.name, folder.parent)}</span> &raquo; #{breadcrumbs}"
    breadcrumbs = breadcrumbs(folder.parent, breadcrumbs) unless folder.parent == Folder.root
    breadcrumbs.html_safe
  end

  def file_icon(extension)
    if FileTest.exists?("#{Rails.root}/public/images/fileicons/#{extension}.png")
      "fileicons/#{extension}.png"
    else
      'file.png'
    end
  end
end

app/views/folders/_form.html.erb
<%= f.error_messages %>
<p>
	<%= f.label :name %>:<br>
	<%= f.text_field :name, { :class => 'text_input' } %>
</p>
<p>
	<%= f.submit 'Save' %> &nbsp; &mdash; &nbsp;
	<%= link_to 'Back', folder_url(@folder.parent) %>
</p>

app/views/folders/edit.html.erb
<% content_for :title, 'Rename folder' -%>

<h1><%= content_for :title %></h1>
<% if flash[:notice] -%>
<p class="notice">
	<%= flash[:notice] %>
</p>
<% end -%>
<%= form_for @folder, :url => { :action => 'update' } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/folders/new.html.erb
<% content_for :title, 'New folder' -%>

<h1><%= content_for :title %></h1>
<%= form_for [@parent_folder, @folder], :url => { :action => 'create' } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/folders/show.html.erb
<% content_for :title, @folder.name -%>

<h1><%= content_for :title %></h1>
<% unless @folder.is_root? -%>
<p>
	<%= breadcrumbs(@folder) %>
	<span class="breadcrumb nowrap"><%= @folder.name %></span>
</p>
<% end -%>
<% if flash[:alert] -%>
<p class="error">
	<%= flash[:alert] %>
</p>
<% end -%>
<p>
<% if current_user.can_create(@folder) -%>
	<%= link_to 'Create a new folder', new_folder_folder_path(@folder) %> or
	<%= link_to 'Upload a file', new_folder_file_path(@folder) %>
<% end -%>
<% if current_user.member_of_admins? -%>
	&nbsp;|&nbsp;
	<%= link_to_function 'Edit permissions', 'show_permissions();', :id => 'show_permissions_link' %>
	<%= link_to_function 'Back to folder', 'hide_permissions();', { :id => 'hide_permissions_link', :style => 'display:none;' } %>
<% end -%>
</p>
<div id="files_and_folders">
	<table>
		<tr>
			<th></th>
			<th>Name</th>
			<th>Size</th>
			<th>Date modified</th>
			<th></th>
		</tr>
	<% unless @folder.is_root? -%>
		<tr class="<%= cycle('even','odd') %>">
			<td><%= image_tag('folder.png') %></td>
			<td class="file_name">&uarr; <%= link_to 'up', folder_path(@folder.parent), :title => @folder.parent.name %></td>
			<td class="file_size">--</td>
			<td class="file_modified">--</td>
			<td></td>
		</tr>
	<% end -%>
	<% @folder.children.each do |folder| -%>
		<% if current_user.can_read(folder) -%>
		<tr class="<%= cycle('even','odd') %>">
			<td><%= image_tag('folder.png') %></td>
			<td class="file_name"><%= link_to folder.name, folder_path(folder) %></td>
			<td class="file_size">--</td>
			<td class="file_modified"><%= folder.updated_at.to_s(:long_ordinal) %></td>
			<td>
			<% if current_user.can_update(folder) -%>
				<%= link_to image_tag('edit.png', :alt => 'Edit'), edit_folder_path(folder), :title => 'Edit' %>&nbsp;
			<% end -%>
			<% if current_user.can_delete(folder) -%>
				<%= link_to image_tag('delete.png', :alt => 'Delete'), folder_path(folder), :method => 'delete', :confirm => 'Are you sure?', :title => 'Delete' %>
			<% end -%>
			</td>
		</tr>
		<% end -%>
	<% end -%>
	<% @folder.user_files.each do |file| -%>
		<% if current_user.can_read(@folder) -%>
		<tr class="<%= cycle('even','odd') %>">
			<td><%= image_tag(file_icon(file.extension)) %></td>
			<td class="file_name"><%= link_to file.attachment_file_name, file_path(file), :title => "Download #{file.attachment_file_name}" %></td>
			<td class="file_size"><%= number_to_human_size(file.attachment_file_size) %></td>
			<td class="file_modified"><%= file.updated_at.to_s(:long_ordinal) %></td>
			<td>
			<% if current_user.can_update(file.folder) -%>
				<%= link_to image_tag('edit.png', :alt => 'Edit'), edit_file_path(file), :title => 'Edit' %>&nbsp;
			<% end -%>
			<% if current_user.can_delete(file.folder) -%>
				<%= link_to image_tag('delete.png', :alt => 'Delete'), file_path(file), :method => 'delete', :confirm => 'Are you sure?', :title => 'Delete' %>
			<% end -%>
			</td>
		</tr>
		<% end -%>
	<% end -%>
	</table>
</div>
<% if current_user.member_of_admins? -%>
<div id="permissions" style="display:none;">
	<%= form_tag update_multiple_permissions_path do %>
		<%= hidden_field_tag '_method', 'put' %>
		<table>
			<tr>
				<th></th>
				<th></th>
				<th class="permission_column">Create</th>
				<th class="permission_column">Read</th>
				<th class="permission_column">Update</th>
				<th class="permission_column">Delete</th>
			</tr>
			<% @folder.permissions.each do |permission| -%>
			<%= fields_for "permissions[]", permission do |f| %>
			<tr class="<%= cycle('even','odd') %>">
				<% if permission.group.admins_group? -%>
					<td><%= image_tag('group_grey.png') %></td>
					<td class="disabled"><%= permission.group.name %></td>
					<td class="permission_column"><input type="checkbox" checked="checked" disabled="disabled" /></td>
					<td class="permission_column"><input type="checkbox" checked="checked" disabled="disabled" /></td>
					<td class="permission_column"><input type="checkbox" checked="checked" disabled="disabled" /></td>
					<td class="permission_column"><input type="checkbox" checked="checked" disabled="disabled" /></td>
				<% else -%>
					<td><%= image_tag('group.png') %></td>
					<td><%= permission.group.name %></td>
					<td class="permission_column"><%= f.check_box :can_create %></td>
					<td class="permission_column"><%= f.check_box :can_read %></td>
					<td class="permission_column"><%= f.check_box :can_update %></td>
					<td class="permission_column"><%= f.check_box :can_delete %></td>
				<% end -%>
			</tr>
			<% end -%>
			<% end -%>
		</table>
		<p class="permissions_button">
			<%= submit_tag 'Save', :class => 'button' %>
			<%= check_box_tag :recursive, true %> Apply changes to subfolders
		</p>
	<% end -%>
</div>
<% end -%>