config/routes.rb
Boxroom::Application.routes.draw do
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/folders/:id/new', :to => 'folders#new'

  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]

  resources :permissions, :only => :update_multiple do
    collection do
      put :update_multiple
    end
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  root :to => "folders#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :permissions
  has_and_belongs_to_many :users

  validates_uniqueness_of :name
  validates_presence_of :name

  after_create :create_admin_permissions, :if => :admins_group?
  after_create :create_permissions, :unless => :admins_group?
  before_destroy :dont_destroy_admins

  def admins_group?
    name == 'Admins'
  end

  private

  def create_admin_permissions
    Permission.create! do |p|
      p.group = self
      p.folder = Folder.find_by_name_and_parent_id('Root folder', nil)
      p.can_create = true
      p.can_read = true
      p.can_update = true
      p.can_delete = true
    end
  end

  def create_permissions
    Folder.all.each do |folder|
      Permission.create! do |p|
        p.group = self
        p.folder = folder
        p.can_create = false
        p.can_read = folder.is_root? # New groups can read the root folder
        p.can_update = false
        p.can_delete = false
      end
    end
  end

  def dont_destroy_admins
    raise "Can't delete admins group" if admins_group?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :require_admin
  before_filter :require_existing_group, :only => [:edit, :update, :destroy]
  before_filter :require_group_isnt_admins_group, :only => [:edit, :update, :destroy]

  # GET /groups
  def index
    @groups = Group.all(:order => 'name')
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups
  def create
    @group = Group.new(params[:group])

    if @group.save
      redirect_to groups_url
    else
      render :action => 'new'
    end
  end

  # GET /groups/:id/edit
  # Note: @group is set in require_existing_group
  def edit
  end

  # PUT /groups/:id
  # Note: @group is set in require_existing_group
  def update
    if @group.update_attributes(params[:group])
      redirect_to edit_group_url(@group), :notice => 'Your changes were saved successfully.'
    else
      render :action => 'edit'
    end
  end

  # DELETE /group/:id
  # Note: @group is set in require_existing_group
  def destroy
    @group.destroy
    redirect_to groups_url
  end

  private

  def require_existing_group
    @group = Group.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to groups_url, :alert => 'Someone else deleted this group. Your action was cancelled.'
  end

  def require_group_isnt_admins_group
    if @group.admins_group?
      redirect_to groups_url, :alert => 'The admins group cannot be deleted or renamed.'
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= f.error_messages %>
<p>
	<%= f.label :name %>:<br>
	<%= f.text_field :name, { :class => 'text_input' } %>
</p>
<p>
	<%= f.submit 'Save' %> &nbsp; &mdash; &nbsp;
	<%= link_to 'Back', groups_url %>
</p>

app/views/groups/edit.html.erb
<% content_for :title, 'Rename group' -%>

<h1><%= content_for :title %></h1>
<% if flash[:notice] -%>
<p class="notice">
	<%= flash[:notice] %>
</p>
<% end -%>
<%= form_for @group, :url => { :action => 'update' } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/groups/index.html.erb
<% content_for :title, 'Groups' -%>

<h1><%= content_for :title %></h1>
<% if flash[:alert] -%>
<p class="error">
	<%= flash[:alert] %>
</p>
<% end -%>
<p>
	<%= link_to 'Create a new group', new_group_path %>
</p>
<table>
	<tr>
		<th></th>
		<th>Name</th>
		<th></th>
	</tr>
<% @groups.each do |group| -%>
	<tr class="<%= cycle('even','odd') %>">
	<% if group.admins_group? -%>
		<td><%= image_tag('group_grey.png') %></td>
		<td class="group_name disabled"><%= group.name %></td>
		<td></td>
	<% else -%>
		<td><%= image_tag('group.png') %></td>
		<td class="group_name"><%= group.name %></td>
		<td>
			<%= link_to image_tag('edit.png', :alt => 'Edit'), edit_group_path(group), :title => 'Edit' %>&nbsp;
			<%= link_to image_tag('delete.png', :alt => 'Delete'), group_path(group), :method => 'delete', :confirm => 'Are you sure?', :title => 'Delete' %>
		</td>
	<% end -%>
	</tr>
<% end -%>
</table>

app/views/groups/new.html.erb
<% content_for :title, 'New group' -%>

<h1><%= content_for :title %></h1>
<%= form_for @group, :url => { :action => 'create' } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>