config/routes.rb
Boxroom::Application.routes.draw do
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/folders/:id/new', :to => 'folders#new'

  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]

  resources :permissions, :only => :update_multiple do
    collection do
      put :update_multiple
    end
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  root :to => "folders#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups

  attr_accessor :password_confirmation, :password_required, :dont_clear_reset_password_token
  attr_accessible :name, :email, :password, :password_confirmation, :password_required

  validates_confirmation_of :password
  validates_length_of :password, :in => 6..20, :allow_blank => true
  validates_presence_of :password, :if => :password_required
  validates_presence_of :name, :email
  validates_uniqueness_of :name, :email
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/

  before_save :clear_reset_password_token, :unless => :dont_clear_reset_password_token
  after_create :create_root_folder_and_admins_group, :if => :is_admin

  ['create', 'read', 'update', 'delete'].each do |method|
    define_method "can_#{method}" do |folder|
      has_permission = false
      groups.each do |group|
        unless group.permissions.send("find_by_folder_id_and_can_#{method}", folder.id, true).blank?
          has_permission = true
          break
        end
      end
      has_permission
    end
  end

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    unless @password.blank?
      self.password_salt = SecureRandom.base64(32)
      self.hashed_password = Digest::SHA256.hexdigest(password_salt + password)
    end
  end

  def member_of_admins?
    !groups.find_by_name('Admins').blank?
  end

  def refresh_reset_password_token
    self.reset_password_token = SecureRandom.hex(16)
    self.reset_password_token_expires_at = 1.hour.from_now
    self.dont_clear_reset_password_token = true
    save(:validate => false)
  end

  def refresh_remember_token
    self.remember_token = SecureRandom.base64(32)
    save(:validate => false)
  end

  def forget_me
    self.remember_token = nil
    save(:validate => false)
  end

  def self.authenticate(name, password)
    user = find_by_name(name) or return nil
    hash = Digest::SHA256.hexdigest(user.password_salt + password)
    hash == user.hashed_password ? user : nil
  end

  def self.no_admin_yet?
    find_by_is_admin(true).blank?
  end

  private

  def clear_reset_password_token
    self.reset_password_token = nil
    self.reset_password_token_expires_at = nil
  end

  def create_root_folder_and_admins_group
    Folder.create(:name => 'Root folder')
    groups << Group.create(:name => 'Admins')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin, :except => [:edit, :update]
  before_filter :require_existing_user, :only => [:edit, :update, :destroy]
  before_filter :require_deleted_user_isnt_admin, :only => :destroy

  # GET /users
  def index
    @users = User.all(:order => 'name')
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(params[:user].merge({ :password_required => true }))

    if @user.save
      set_groups
      redirect_to users_url
    else
      render :action => 'new'
    end
  end

  # GET /users/:id/edit
  # Note: @user is set in require_existing_user
  def edit
  end

  # PUT /users/:id
  # Note: @user is set in require_existing_user
  def update
    if @user.update_attributes(params[:user].merge({ :password_required => false }))
      set_groups
      redirect_to edit_user_url(@user), :notice => 'Your changes were saved successfully.'
    else
      render :action => 'edit'
    end
  end

  # DELETE /user/:id
  # Note: @user is set in require_existing_user
  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def require_existing_user
    if current_user.member_of_admins? && params[:id] != current_user.id.to_s
      @title = 'Edit user'
      @user = User.find(params[:id])
    else
      @title = 'Account settings'
      @user = current_user
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to users_url, :alert => 'Someone else deleted the user. Your action was cancelled.'
  end

  def require_deleted_user_isnt_admin
    if @user.is_admin
      redirect_to users_url, :alert => 'The admin user cannot be deleted.'
    end
  end

  def set_groups
    if current_user.member_of_admins?
      @user.group_ids = params[:user][:group_ids]
      @user.groups << Group.find_by_name('Admins') if @user.is_admin
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_belongs_to_group(group)
    unless @user.nil?
      @user.groups.include?(group)
    end
  end
end

app/views/users/_form.html.erb
<%= f.error_messages %>
<p>
	<%= f.label :name %>:<br>
	<%= f.text_field :name, { :class => 'text_input' } %>
</p>
<p>
	<%= f.label :email %>:<br>
	<%= f.text_field :email, { :class => 'text_input' } %>
</p>
<p>
	<%= label_tag :password %>:<br>
	<%= f.password_field :password, { :class => 'text_input' } %>
</p>
<p>
	<%= label_tag :confirm_password %>:<br>
	<%= f.password_field :password_confirmation, { :class => 'text_input' } %>
</p>
<% if current_user.member_of_admins? -%>
<p>
	Member of these groups:
	<span class="user_groups">
	<% Group.all.each do |group| -%>
	<% if @user.is_admin && group.admins_group? -%>
		<span class="group nowrap disabled">
			<input type="checkbox" checked="checked" disabled="disabled" />
			<%= group.name %>
		</span>
	<% else -%>
		<span class="group nowrap">
			<%= check_box_tag('user[group_ids][]', group.id, user_belongs_to_group(group)) %>
			<%= group.name %>
		</span>
	<% end -%>
	<% end -%>
	</span>
</p>
<% end -%>
<p>
	<%= f.submit 'Save' %>
<% if @user != current_user -%>
	&nbsp; &mdash; &nbsp;
	<%= link_to 'Back', users_url %>
<% end -%>
</p>

app/views/users/edit.html.erb
<% content_for :title, @title -%>

<h1><%= content_for :title %></h1>
<% if flash[:notice] -%>
<p class="notice">
	<%= flash[:notice] %>
</p>
<% end -%>
<%= form_for @user, :url => { :action => 'update' } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/users/index.html.erb
<% content_for :title, 'Users' -%>

<h1><%= content_for :title %></h1>
<% if flash[:alert] -%>
<p class="error">
	<%= flash[:alert] %>
</p>
<% end -%>
<p>
	<%= link_to 'Create a new user', new_user_path %>
</p>
<table>
	<tr>
		<th></th>
		<th>Name</th>
		<th>Email</th>
		<th></th>
	</tr>
<% @users.each do |user| -%>
	<tr class="<%= cycle('even','odd') %>">
		<td><%= image_tag('user.png') %></td>
		<td class="user_name"><%= user.name %></td>
		<td class="user_email"><%= user.email %></td>
		<td>
			<%= link_to image_tag('edit.png', :alt => 'Edit'), edit_user_path(user), :title => 'Edit' %>&nbsp;
		<% unless user.is_admin -%>
			<%= link_to image_tag('delete.png', :alt => 'Delete'), user_path(user), :method => 'delete', :confirm => 'Are you sure?', :title => 'Delete' %>
		<% end -%>
		</td>
	</tr>
<% end -%>
</table>

app/views/users/new.html.erb
<% content_for :title, 'New user' -%>

<h1><%= content_for :title %></h1>
<%= form_for @user, :url => { :action => 'create' } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>