config/routes.rb
Boxroom::Application.routes.draw do
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/folders/:id/new', :to => 'folders#new'

  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]

  resources :permissions, :only => :update_multiple do
    collection do
      put :update_multiple
    end
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  root :to => "folders#index"

end

app/views/shared/_footer.html.erb
<div id="footer">
	<p class="footer">
		<a href="http://boxroom.rubyforge.org">Boxroom</a> is developed by Mischa Berger
		and released under the <a href="http://opensource.org/licenses/mit-license.php">MIT license</a>
	</p>
</div>

app/views/shared/_header.html.erb
<div id="header">
	<% if signed_in? -%>
	<div class="user_welcome">
		<p>
			Hello, <%= current_user.name %>!<br>
			<%= link_to 'Settings', edit_user_path(current_user) %> | <%= link_to 'Sign out', signout_path %>
		</p>
	</div>
	<% end -%>
	<%= link_to image_tag('logo.png', :alt => 'Boxroom'), root_path %>
</div>

app/views/shared/_menu.html.erb
<div id="menu">
	<p class="menu">
	<% if signed_in? -%>
		<%= link_to 'Folders', folders_path %> &nbsp; &nbsp;
	<% if current_user.member_of_admins? -%>
		<%= link_to 'Users', users_path %> &nbsp; &nbsp;
		<%= link_to 'Groups', groups_path %> &nbsp; &nbsp;
	<% end -%>
	<% else -%>
		<%= link_to 'Sign in', new_session_path %> &nbsp; &nbsp;
	<% end -%>
	</p>
</div>